config/routes.rb
Rails.application.routes.draw do
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update, :show]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get 'welcome/index'
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  get "/users/:id" => "users#show"

  root 'welcome#index'

end

app/models/listing.rb
class Listing < ActiveRecord::Base
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
    
    def index
    end
    
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController
    
#  before_action :find_user, only: [:show, :edit, :update]
# def index
#     @users = User.all
# end
def profile
    redirect_to user_path(current_user)
end
  
def create
   # @user = User.new(user_params)
# byebug
   @user = user_from_params
   
   if @user.save
     sign_in @user
     redirect_back_or url_after_create
   else
     render template: "users/new"
   end
end

 def show
   @user = User.find_by_id(params[:id])
 end

 def edit
    @user = User.find_by_id(params[:id])
 end

 def update
   @user = User.find_by_id(params[:id])
   if @user.update_attributes(user_params)
     flash[:notice] = "Successfully Updated"
   else
     flash[:notice] = @user.errors.full_messages
   end
     render 'edit'
 end

private

 # def user_params
 #   params.require(:user).permit(:username, :email, :password, :name, :encrypted_password, :confirmation_token)
 # end #
 
  def user_from_params
   # byebug
    email = user_params.delete(:email)
    password = user_params.delete(:password)
    username = user_params.delete(:username)
    name = user_params.delete(:name)

    Clearance.configuration.user_model.new(user_params).tap do |user|
      user.email = email
      user.password = password
      user.username = username
      user.name = name
    end
  end

  def user_params
   # byebug
    params[Clearance.configuration.user_parameter] || Hash.new
  end

 
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tag %>
</head>
<body>
  
  
  <div id="header">
    <% if signed_in? -%>
      <%= link_to 'Profile', user_path(current_user) %>
      <%= button_to t(".sign_out"), sign_out_path, method: :delete %>
    <% else -%>
      <%= link_to t(".sign_in"), sign_in_path %>
    <% end -%>
  </div>

  <div id="flash">
    <% flash.each do |key, value| -%>
      <div id="flash_<%= key %>"><%=h value %></div>
    <% end %>
  </div>

  <%= yield %>
</body>
</html>

app/views/users/_form.html.erb
<div class="username-field">
  <%= form.label :username %>
  <%= form.text_field :username %>
</div>

<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

<div class="name-field">
  <%= form.label :name %>
  <%= form.text_field :name %>
</div>

app/views/users/index.html.erb
index

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %> 
    </div>

   
  <% end %>
</div>



    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>

app/views/users/show.html.erb
<div id="container">
  <h2>Your Profile</h2>
  <h3>Name : <%= @user.name%></h3>
  <h3>Username : <%= @user.username%></h3>
  <h3>Email : <%= @user.email%></h3>

  <%= link_to "Edit", edit_user_path(@user) %>
</div>

app/views/welcome/index.html.erb
<!--<h1>Welcome#index</h1>-->
<!--<p>Find me in app/views/welcome/index.html.erb</p>-->


<center>
<div id="welcome_text_div">
            <h1 id="welcome_text">Welcome to Home</h1>
            <p id="welcome_under_text">Where you can find your peace.</p>
            <a href="#" id="how_it_works">
                How It Works
            </a>
            
</div>     
</center>


-> /welcome/index